from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(include_in_schema=False)

# The browser console is intentionally embedded with the other RoadTalk browser surfaces.
# ruff: noqa: E501
_ADMIN_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoadTalk | Administration</title>
<style>:root{color-scheme:dark;--bg:#07141b;--panel:#10232e;--text:#f2f7f9;--muted:#8fa7b2;--accent:#f2b84b;--bad:#ff7979;--line:rgba(255,255,255,.1)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{width:min(1100px,calc(100% - 28px));margin:auto}header{padding:18px 0;border-bottom:1px solid var(--line)}nav,.row,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}nav{justify-content:space-between}a,button,input{font:inherit}a,button{border:1px solid var(--line);border-radius:10px;padding:9px 11px;background:rgba(255,255,255,.04);color:var(--text);text-decoration:none}button{cursor:pointer}button.danger{border-color:var(--bad)}main{padding:28px 0}.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px;margin-bottom:14px}.muted{color:var(--muted)}.bad{color:var(--bad)}input{background:#081820;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px;min-width:280px}.account{border-top:1px solid var(--line);padding:15px 0}.account:first-child{border-top:0}.meta{color:var(--muted);font-size:.9rem;overflow-wrap:anywhere}</style></head>
<body><header><div class="wrap"><nav><strong>RoadTalk Administration</strong><div><a href="/">Home</a> <a href="/ops">Operations</a> <a href="/account">Account</a></div></nav></div></header>
<main class="wrap"><section class="card"><h1>Account support</h1><p id="status" role="status">Verifying administrator authorization…</p><p class="muted">Support-safe account metadata only. Passwords, recovery keys, raw location/history, and media/provider secrets are never displayed here.</p><div class="row"><input id="query" maxlength="128" placeholder="Search call sign or exact account UUID"><button id="search">Search</button></div></section><section id="results" class="card" hidden></section></main>
<script>
const $=id=>document.getElementById(id);let access=localStorage.getItem('rt_access'),refreshToken=localStorage.getItem('rt_refresh');
async function refresh(){if(!refreshToken)return false;const r=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!r.ok)return false;const b=await r.json();access=b.access_token;refreshToken=b.refresh_token;localStorage.setItem('rt_access',access);localStorage.setItem('rt_refresh',refreshToken);return true}
async function api(path,opts={}){if(!access)throw new Error('Sign in before opening Administration.');const request=()=>fetch(path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+access,...opts.headers}});let r=await request();if(r.status===401&&await refresh())r=await request();if(!r.ok){let b={};try{b=await r.json()}catch{}throw new Error(b.detail?.detail||'HTTP '+r.status)}return r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){try{const q=$('query').value.trim();const data=await api('/api/v1/admin/accounts?limit=50'+(q?'&q='+encodeURIComponent(q):''));$('status').textContent='Administrator access verified.';$('results').hidden=false;$('results').innerHTML=data.accounts.length?data.accounts.map(a=>'<div class="account"><strong>'+esc(a.callsign||'No call sign')+'</strong><div class="meta">'+esc(a.account_id)+' · '+esc(a.account_type)+' · '+esc(a.status)+' · '+a.device_count+' device(s) · '+a.active_session_count+' active session(s)</div><div class="actions"><button data-action="'+(a.status==='disabled'?'enable':'disable')+'" data-id="'+a.account_id+'" class="'+(a.status==='disabled'?'':'danger')+'">'+(a.status==='disabled'?'Enable account':'Disable account')+'</button><button data-action="revoke-sessions" data-id="'+a.account_id+'">Revoke sessions</button></div></div>').join(''):'<p class="muted">No accounts matched.</p>'}catch(e){$('status').textContent=e.message;$('status').className='bad';$('results').hidden=true}}
$('search').onclick=load;$('query').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('results').onclick=async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;if(!confirm('Confirm '+action.replace('-',' ')+' for account '+id+'?'))return;try{await api('/api/v1/admin/accounts/'+id+'/'+action,{method:'POST',body:JSON.stringify({confirm:true})});await load()}catch(err){alert(err.message)}};load();
</script></body></html>"""


@router.get("/admin", response_class=HTMLResponse)
async def admin_console() -> HTMLResponse:
    return HTMLResponse(_ADMIN_PAGE)
