# ruff: noqa: E501

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(include_in_schema=False)


@router.get("/convoys", response_class=HTMLResponse)
async def convoys_page() -> HTMLResponse:
    return HTMLResponse(r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoadTalk | Convoys</title><style>:root{color-scheme:dark;--bg:#07141b;--panel:#10232e;--text:#f2f7f9;--muted:#abc0c9;--accent:#f2b84b;--bad:#ff7979;--line:rgba(255,255,255,.14)}*{box-sizing:border-box}body{margin:auto;max-width:850px;padding:24px;background:var(--bg);color:var(--text);font-family:system-ui}nav,.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.panel{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:18px;margin:18px 0}.muted{color:var(--muted)}input,button{padding:11px;background:#07141b;color:#fff;border:1px solid #78909a;border-radius:8px}input{width:100%}button{cursor:pointer}button.danger{border-color:var(--bad)}button:disabled{opacity:.55;cursor:not-allowed}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.field{display:grid;gap:7px;margin:12px 0}.hidden{display:none}.member{padding:9px 0;border-top:1px solid var(--line)}</style></head><body><nav aria-label="RoadTalk"><strong>RoadTalk Convoys</strong><a href="/">Home</a><a href="/radio">Radio</a><a href="/map">Map</a><a href="/audience">Audience</a></nav><main><h1>Travel together without location history.</h1><p class="muted">Convoys label and narrow existing RoadTalk context. Membership never grants communication access, and this page does not display coordinates, routes, or movement history.</p><p id="status" role="status" aria-live="polite">Loading convoy status…</p><section id="none" class="panel hidden"><h2>Start or join a convoy</h2><form id="create"><label class="field">Convoy name<input id="name" maxlength="64" required autocomplete="off"></label><button type="submit">Create convoy</button></form><hr><form id="join"><label class="field">Convoy ID<input id="convoy-id" required autocomplete="off" inputmode="text"></label><button type="submit">Join convoy</button></form></section><section id="active" class="panel hidden"><h2 id="convoy-name">Current convoy</h2><p id="role" class="muted"></p><div id="members" aria-label="Current convoy members"></div><div class="row"><button id="leave" class="danger hidden" type="button">Leave convoy</button><button id="disband" class="danger hidden" type="button">Disband convoy</button></div></section></main><script>
const $=id=>document.getElementById(id);let current=null,busy=false;
const access=()=>localStorage.getItem('rt_access'),refreshToken=()=>localStorage.getItem('rt_refresh');
async function refresh(){const t=refreshToken();if(!t)return false;const r=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:t})});if(!r.ok)return false;const b=await r.json();localStorage.setItem('rt_access',b.access_token);localStorage.setItem('rt_refresh',b.refresh_token);return true}
async function api(path,opts={}){let t=access();if(!t)throw Error('Sign in from Account or Radio first.');const send=()=>fetch(path,{...opts,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${access()}`,...(opts.headers||{})}});let r=await send();if(r.status===401&&await refresh())r=await send();if(!r.ok){let b={};try{b=await r.json()}catch{}throw Error(b.detail?.detail||b.detail?.code||'Convoy request failed.')}if(r.status===204)return null;return r.json()}
function show(id,on){$(id).classList.toggle('hidden',!on)}function lock(on){busy=on;document.querySelectorAll('button,input').forEach(x=>x.disabled=on)}
async function paint(){show('none',!current);show('active',!!current);if(!current)return;$('convoy-name').textContent=current.display_name;$('role').textContent=current.role==='leader'?'You lead this convoy.':'You are a convoy member.';show('leave',current.role==='member');show('disband',current.role==='leader');$('members').replaceChildren();try{const a=await api('/api/v1/convoys/awareness');if(!a||!a.members.length){$('members').textContent='No members currently have eligible foreground current state.';return}for(const x of a.members){const p=document.createElement('p');p.className='member';p.textContent=x.callsign+' · '+x.role+' · current';$('members').appendChild(p)}}catch{$('members').textContent='Current convoy awareness is temporarily unavailable.'}}
async function load(){try{current=await api('/api/v1/convoys/me');$('status').textContent=current?'Convoy status loaded.':'You are not currently in an active convoy.';await paint()}catch(e){$('status').textContent=e.message;show('none',false);show('active',false)}}
$('create').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;lock(true);try{current=await api('/api/v1/convoys',{method:'POST',body:JSON.stringify({display_name:$('name').value})});$('status').textContent='Convoy created.';await paint()}catch(err){$('status').textContent=err.message}finally{lock(false)}});
$('join').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;lock(true);try{current=await api('/api/v1/convoys/join',{method:'POST',body:JSON.stringify({convoy_id:$('convoy-id').value})});$('status').textContent='Convoy joined.';await paint()}catch(err){$('status').textContent=err.message}finally{lock(false)}});
$('leave').addEventListener('click',async()=>{if(busy||!confirm('Leave this convoy? You will lose its convoy context.'))return;lock(true);try{await api('/api/v1/convoys/leave',{method:'POST',body:'{}'});current=null;$('status').textContent='You left the convoy.';await paint()}catch(err){$('status').textContent=err.message}finally{lock(false)}});
$('disband').addEventListener('click',async()=>{if(busy||!confirm('Disband this convoy for every member? This cannot be undone.'))return;lock(true);try{await api('/api/v1/convoys/disband',{method:'POST',body:'{}'});current=null;$('status').textContent='Convoy disbanded.';await paint()}catch(err){$('status').textContent=err.message}finally{lock(false)}});void load();
</script></body></html>""")
