# ruff: noqa: E501

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(include_in_schema=False)

_PAGE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoadTalk | Safety controls</title><style>:root{color-scheme:dark;--bg:#07141b;--panel:#10232e;--text:#f2f7f9;--muted:#abc0c9;--accent:#f2b84b;--bad:#ff7979;--line:rgba(255,255,255,.14)}*{box-sizing:border-box}body{margin:auto;max-width:900px;padding:24px;background:var(--bg);color:var(--text);font-family:system-ui}nav,.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.panel{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:18px;margin:18px 0}.muted{color:var(--muted)}input,select,button{padding:11px;background:#07141b;color:#fff;border:1px solid #78909a;border-radius:8px}input,select{width:100%}button{cursor:pointer}button.danger{border-color:var(--bad)}button:disabled{opacity:.55}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.field{display:grid;gap:7px;margin:12px 0}.item{padding:12px 0;border-top:1px solid var(--line)}</style></head><body><nav aria-label="RoadTalk"><strong>RoadTalk Safety</strong><a href="/">Home</a><a href="/radio">Radio</a><a href="/account">Account</a></nav><main><h1>Report, mute, or block an account</h1><p class="muted">Use the account ID shown by an authorized RoadTalk interaction. These controls do not reveal whether another account exists, its location, route, device, channel, convoy, or moderation state.</p><p id="status" role="status" aria-live="polite">Checking your session…</p><section class="panel"><h2>Safety action</h2><form id="action"><label class="field">Account ID<input id="subject" required autocomplete="off"></label><label class="field">Action<select id="kind"><option value="mute">Mute</option><option value="block">Block</option><option value="report">Report</option></select></label><label id="reason-field" class="field" hidden>Report reason<select id="reason"><option value="harassment">Harassment</option><option value="spam">Spam</option><option value="impersonation">Impersonation</option><option value="unsafe_content">Unsafe content</option><option value="other">Other</option></select></label><button type="submit">Continue</button></form></section><section class="panel"><h2>Active mute and block controls</h2><button id="refresh" type="button">Refresh</button><div id="items" aria-live="polite"><p class="muted">Loading…</p></div></section></main><script>
const $=id=>document.getElementById(id);let access=()=>localStorage.getItem('rt_access'),refreshToken=()=>localStorage.getItem('rt_refresh'),busy=false;
async function refreshAuth(){const t=refreshToken();if(!t)return false;const r=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:t})});if(!r.ok)return false;const b=await r.json();localStorage.setItem('rt_access',b.access_token);localStorage.setItem('rt_refresh',b.refresh_token);return true}
async function api(path,opts={}){if(!access())throw Error('Sign in from Account first.');const send=()=>fetch(path,{...opts,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${access()}`,...(opts.headers||{})}});let r=await send();if(r.status===401&&await refreshAuth())r=await send();if(!r.ok){let b={};try{b=await r.json()}catch{}throw Error(b.detail?.detail||'Moderation action is unavailable.')}if(r.status===204)return null;return r.json()}
function lock(on){busy=on;document.querySelectorAll('button,input,select').forEach(x=>x.disabled=on)}
$('kind').onchange=()=>{$('reason-field').hidden=$('kind').value!=='report'};
async function load(){try{const body=await api('/api/v1/moderation/restrictions');$('status').textContent='Safety controls ready.';const items=body.items||[];$('items').replaceChildren();if(!items.length){$('items').innerHTML='<p class="muted">No active mute or block controls.</p>';return}for(const x of items){const p=document.createElement('div');p.className='item';const label=document.createElement('span');label.textContent=`${x.kind==='block'?'Blocked':'Muted'} account ${x.subject_account_id}`;const b=document.createElement('button');b.type='button';b.className='danger';b.textContent=x.kind==='block'?'Unblock':'Unmute';b.onclick=()=>remove(x.restriction_id);p.append(label,' ',b);$('items').appendChild(p)}}catch(e){$('status').textContent=e.message;$('items').innerHTML='<p class="muted">Safety controls are temporarily unavailable. Existing server-side restrictions remain enforced.</p>'}}
async function remove(id){if(busy||!confirm('Remove this safety restriction?'))return;lock(true);try{await api(`/api/v1/moderation/restrictions/${id}`,{method:'DELETE'});$('status').textContent='Restriction removed.';await load()}catch(e){$('status').textContent=e.message}finally{lock(false)}}
$('action').onsubmit=async e=>{e.preventDefault();if(busy)return;const subject=$('subject').value.trim(),kind=$('kind').value;if(!confirm(`${kind==='report'?'Submit this report':'Apply this '+kind}?`))return;lock(true);try{if(kind==='report'){await api('/api/v1/moderation/reports',{method:'POST',body:JSON.stringify({subject_account_id:subject,reason:$('reason').value,idempotency_key:`web-${crypto.randomUUID()}`})});$('status').textContent='Report submitted.'}else{await api('/api/v1/moderation/restrictions',{method:'POST',body:JSON.stringify({subject_account_id:subject,kind})});$('status').textContent=kind==='block'?'Account blocked.':'Account muted.';await load()}$('subject').value=''}catch(err){$('status').textContent=err.message}finally{lock(false)}};
$('refresh').onclick=()=>load();void load();
</script></body></html>"""


@router.get("/safety", response_class=HTMLResponse)
async def moderation_page() -> HTMLResponse:
    return HTMLResponse(_PAGE)
