# ruff: noqa: E501

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(include_in_schema=False)

_NOTIFICATIONS_PAGE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoadTalk | Notifications</title>
<style>:root{color-scheme:dark;--bg:#07141b;--panel:#10232e;--text:#f2f7f9;--muted:#8fa7b2;--accent:#f2b84b;--green:#70da96;--red:#ff7979;--line:rgba(255,255,255,.1)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{width:min(900px,calc(100% - 28px));margin:auto}header{border-bottom:1px solid var(--line);padding:18px 0}.nav,.actions,.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.nav{justify-content:space-between}.links{display:flex;gap:8px;flex-wrap:wrap}a,button,textarea,input{font:inherit}a,button{border:1px solid var(--line);border-radius:10px;padding:10px 12px;background:rgba(255,255,255,.04);color:var(--text);text-decoration:none;cursor:pointer}button.primary{background:var(--accent);color:#172028;font-weight:900;border:0}main{padding:28px 0}.card{border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:20px;margin-bottom:16px}h1,h2,h3{margin-top:0}.muted{color:var(--muted)}.bad{color:var(--red)}.good{color:var(--green)}label{display:flex;gap:8px;align-items:center}textarea{width:100%;min-height:92px;background:#081820;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:11px}.notice{border-left:4px solid var(--accent);padding-left:12px}.item{border-top:1px solid var(--line);padding:16px 0}.item:first-child{border-top:0}.urgent{border-left:4px solid var(--red);padding-left:14px}.meta{font-size:.9rem;color:var(--muted);margin:.35rem 0}.warning{font-weight:800}.spacer{flex:1}</style></head>
<body><header><div class="wrap nav"><strong>RoadTalk Notifications</strong><div class="links"><a href="/">Web Radio</a><a href="/map">Map</a><a href="/audience">Audience</a><a href="/account">Account</a></div></div></header><main class="wrap">
<section class="card"><h1>Notifications</h1><p id="status" role="status" aria-live="polite">Checking your persistent account…</p><p class="muted">This is an in-app RoadTalk inbox. Browser push is not active; no external notification provider is configured.</p></section>
<section class="card"><h2>Preferences</h2><div class="row"><label><input id="channel-pref" type="checkbox"> Channel activity</label><label><input id="urgent-pref" type="checkbox"> Urgent alerts</label><button id="save-prefs">Save preferences</button></div><p id="pref-status" class="muted" role="status" aria-live="polite"></p></section>
<section class="card"><h2>Send urgent alert</h2><div class="notice"><p class="warning">RoadTalk is not an emergency service. Delivery is not guaranteed.</p><p>Urgent alerts are user-generated and unverified. Contact local emergency services directly when emergency assistance is needed.</p></div><label for="urgent-message" class="muted">Alert message, up to 280 characters</label><textarea id="urgent-message" maxlength="280" aria-describedby="urgent-warning"></textarea><p id="urgent-warning" class="muted">Recipients are selected only by RoadTalk's existing current channel/proximity authorization. You cannot target a person, location, radius, route, or destination.</p><div class="actions"><button id="send-urgent" class="primary">Send urgent alert</button><span id="urgent-status" role="status" aria-live="polite"></span></div></section>
<section class="card"><div class="row"><h2>Inbox</h2><span class="spacer"></span><button id="refresh">Refresh</button></div><div id="inbox" aria-live="polite"><p class="muted">Loading…</p></div></section>
</main><script>
const $=id=>document.getElementById(id);let access=localStorage.getItem('rt_access'),refreshToken=localStorage.getItem('rt_refresh'),prefVersion=null;
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function parseProblem(response){let body={};try{body=await response.json()}catch{}return new Error(body.detail?.detail||body.detail||`HTTP ${response.status}`)}
function store(body){access=body.access_token;refreshToken=body.refresh_token;localStorage.setItem('rt_access',access);localStorage.setItem('rt_refresh',refreshToken)}
async function ensureSession(){if(!access&&!refreshToken){location.replace('/account');return null}let r=access?await fetch('/api/v1/auth/session',{headers:{Authorization:`Bearer ${access}`}}):null;if((!r||r.status===401)&&refreshToken){const rr=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(rr.ok){store(await rr.json());r=await fetch('/api/v1/auth/session',{headers:{Authorization:`Bearer ${access}`}})}}if(!r||!r.ok){location.replace('/account');return null}const session=await r.json();if(session.account_type!=='registered'){$('status').textContent='Notifications require a persistent registered account. Open Account to protect this guest profile.';$('status').className='bad';return null}$('status').textContent='Persistent account ready.';$('status').className='good';return session}
async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${access}`};const r=await fetch(path,{...options,headers});if(!r.ok)throw await parseProblem(r);return r.json()}
function relative(iso){const seconds=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));if(seconds<60)return `${seconds}s ago`;const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes}m ago`;return `${Math.floor(minutes/60)}h ago`}
function expiry(iso){const seconds=Math.round((new Date(iso).getTime()-Date.now())/1000);if(seconds<=0)return 'expired';if(seconds<60)return `expires in ${seconds}s`;const minutes=Math.floor(seconds/60);return `expires in ${minutes}m`}
async function loadPreferences(){const p=await api('/api/v1/me/notification-preferences');prefVersion=p.version;$('channel-pref').checked=p.channel_activity_enabled;$('urgent-pref').checked=p.urgent_alert_enabled}
async function loadInbox(){const body=await api('/api/v1/me/notifications');const items=body.items||[];if(!items.length){$('inbox').innerHTML='<p class="muted">No current notifications.</p>';return}$('inbox').innerHTML=items.map(n=>{const urgent=n.notification_class==='urgent_alert';const title=n.title|| (urgent?'Urgent RoadTalk alert':'RoadTalk notification');const safety=urgent?`<p class="warning">${escapeHtml(n.safety_unverified)} ${escapeHtml(n.safety_not_emergency_service)} ${escapeHtml(n.safety_delivery_not_guaranteed)}</p><p>${escapeHtml(n.safety_emergency_services_guidance)}</p>`:'';return `<article class="item ${urgent?'urgent':''}" data-id="${n.id}" data-version="${n.version}"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(n.message)}</p><p class="meta">Source: ${escapeHtml(n.source)} · ${relative(n.issued_at)} · ${expiry(n.expires_at)}${n.channel_label?` · Channel: ${escapeHtml(n.channel_label)}`:''}</p>${safety}<div class="actions">${n.read_at?'':'<button data-action="read">Mark read</button>'}<button data-action="dismissed">Dismiss</button></div></article>`}).join('')}
async function loadAll(){const session=await ensureSession();if(!session)return;try{await Promise.all([loadPreferences(),loadInbox()])}catch(e){$('status').textContent=e.message;$('status').className='bad'}}
$('save-prefs').onclick=async()=>{try{if(prefVersion===null)return;$('pref-status').textContent='Saving…';const p=await api('/api/v1/me/notification-preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel_activity_enabled:$('channel-pref').checked,urgent_alert_enabled:$('urgent-pref').checked,expected_version:prefVersion})});prefVersion=p.version;$('pref-status').textContent='Preferences saved.';$('pref-status').className='good'}catch(e){$('pref-status').textContent=e.message;$('pref-status').className='bad'}};
$('send-urgent').onclick=async()=>{try{const message=$('urgent-message').value.trim();if(!message)throw new Error('Enter an urgent alert message.');$('urgent-status').textContent='Sending to the currently authorized RoadTalk audience…';const body=await api('/api/v1/notifications/urgent-alerts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,idempotency_key:`web-${crypto.randomUUID()}`})});$('urgent-status').textContent=`Alert accepted for ${body.recipient_count} currently authorized account${body.recipient_count===1?'':'s'}; delivery/read/response is not guaranteed.`;$('urgent-status').className='good';$('urgent-message').value=''}catch(e){$('urgent-status').textContent=e.message;$('urgent-status').className='bad'}};
$('refresh').onclick=()=>loadInbox().catch(e=>{$('status').textContent=e.message;$('status').className='bad'});
$('inbox').onclick=async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const item=button.closest('[data-id]');try{await api(`/api/v1/me/notifications/${item.dataset.id}/state`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:button.dataset.action,expected_version:Number(item.dataset.version)})});await loadInbox()}catch(e){$('status').textContent=e.message;$('status').className='bad'}};
loadAll();setInterval(()=>{document.querySelectorAll('.item .meta').forEach(()=>{});},30000);
</script></body></html>"""


@router.get("/notifications", response_class=HTMLResponse)
async def notifications_console() -> HTMLResponse:
    return HTMLResponse(_NOTIFICATIONS_PAGE)
